config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  # get 'home/services'
  # get 'home/projects'
  # get 'home/pricing'
  # get 'home/contacts'
  # get 'home/abouat'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  post 'home/contacts', to: 'home#contacts'
  get '/curriculum', to: 'home#curriculum'
  get '/pricing', to: 'home#pricing'
  get '/blog', to: 'home#blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def services
  end

  def projects
  end

  def pricing
  end

  def contacts
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path, notice: "Your message has been sent."
    else
      redirect_to root_path, notice: "Your message has not been sent."
    end
  end

  def abouat
  end

  def curriculum 
  end

  def blog
  end

  private 

  def contact_params
    params.permit(:name, :email, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_accelerate.html.erb
<section class="mt-10">
  <div class="container py-5">
    <div class="row d-flex flex-wrap justify-content-center align-items-center">
      <div class="col-md-6">
        <div class="">
          <h2 class="">
            <span class="fw-bold">
              Fast-Track Your Progress through Personalized 1-on-1 Mentorship
            </span>
          </h2>
          <p class="text-muted fw-bold">
            Refine Your Focus and Forge a Strong Foundation, Empowering You to
            Select Your Ideal Job Path. No More Settling for Less. Our Mentorship
            Program Equips You to Master Every Aspect of Full Stack Development.
          </p>
          <div class="d-flex">
            <a
              class="btn primary-btn btn-lg mt-3 text-light"
              href="/curriculum"
              role="button"
              >Explore Our Curriculum</a
            >
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <%= image_tag "svg/math.svg", class: 'img-fluid' %>
      </div>
    </div>

    <div class="row mt-5 d-flex flex-wrap justify-content-center align-items-center">
      <div class="col-md-6">
        <%= image_tag "svg/steps.svg", class: 'img-fluid' %>
      </div>
      <div class="col-md-6">
        <h2 class="">
          <span class="hero-text fw-bold"> Experience Comprehensive Exploration </span>
        </h2>
        <p class="text-muted fw-bold">
          Delve Beyond Boundaries as We Navigate Through a Spectrum of
          Independent Components, Ensuring Your Mastery of Interviewing Skills
          and Upskilling.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/home/_contact.html.erb
<section class="py-5">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-8 col-xl-6 text-center mx-auto">
        <h2 class="">Ask Us</h2>
        <div class="seperator-line mx-auto"></div>
        <p
          class="text-muted"
        >
          Feel Free to Connect with Us for Any Queries or Information. Our Team Typically Replies Within 24 Hours.
        </p>
      </div>
    </div>
    <div class="row d-flex justify-content-center">
      <div class="col-md-6 col-xl-4">
      <div>
        <%= form_with(url: home_contacts_path, method: :post, data: { bs_theme: 'light' }, class: 'p-3 p-xl-4', id: 'contact-form') do |form| %>
          <div class="mb-3">
            <%= form.text_field :name, class: 'form-control', id: 'name-1', placeholder: 'Name' %>
          </div>
          <div class="mb-3">
            <%= form.email_field :email, class: 'form-control', id: 'email-1', placeholder: 'Email' %>
          </div>
          <div class="mb-3">
            <%= form.text_area :message, class: 'form-control', id: 'message-1', rows: 6, placeholder: 'Your Inquiry' %>
          </div>
          <div>
            <%= form.submit class: 'contact-button shadow d-block w-100 g-recaptcha', 'data-sitekey': "6Lcnyq4nAAAAAHWq7pCyV1XIaSQw0mrhEqAEylq3", 'data-callback': 'onSubmit', 'data-action': 'submit' do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="white" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-send"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>
              Submit
            <% end %>
          </div>
        <% end %>
      </div>

      </div>
      <div
        class="col-md-4 col-xl-4 d-flex justify-content-center justify-content-xl-start"
      >
        <div
          class="d-flex flex-wrap flex-md-column justify-content-md-start align-items-md-start h-100"
        >
          <div class="d-flex align-items-center p-3">
            <div
              class="bs-icon-md bs-icon-circle bs-icon-success shadow d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block bs-icon bs-icon-md"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="1em"
                height="1em"
                fill="#fff"
                viewBox="0 0 16 16"
                class="bi bi-envelope"
              >
                <path
                  d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"
                ></path>
              </svg>
            </div>
            <div class="px-2">
              <h6 class="fw-bold mb-0">Email</h6>
              <p class="text-muted mb-0">info@codingtutor.online</p>
            </div>
          </div>
          <div class="d-flex align-items-center p-3">
            <div
              class="bs-icon-md bs-icon-circle bs-icon-dark shadow d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block bs-icon bs-icon-md"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="1em"
                height="1em"
                fill="#fff"
                viewBox="0 0 16 16"
                class="bi bi-pin"
              >
                <path
                  d="M4.146.146A.5.5 0 0 1 4.5 0h7a.5.5 0 0 1 .5.5c0 .68-.342 1.174-.646 1.479-.126.125-.25.224-.354.298v4.431l.078.048c.203.127.476.314.751.555C12.36 7.775 13 8.527 13 9.5a.5.5 0 0 1-.5.5h-4v4.5c0 .276-.224 1.5-.5 1.5s-.5-1.224-.5-1.5V10h-4a.5.5 0 0 1-.5-.5c0-.973.64-1.725 1.17-2.189A5.921 5.921 0 0 1 5 6.708V2.277a2.77 2.77 0 0 1-.354-.298C4.342 1.674 4 1.179 4 .5a.5.5 0 0 1 .146-.354zm1.58 1.408-.002-.001.002.001zm-.002-.001.002.001A.5.5 0 0 1 6 2v5a.5.5 0 0 1-.276.447h-.002l-.012.007-.054.03a4.922 4.922 0 0 0-.827.58c-.318.278-.585.596-.725.936h7.792c-.14-.34-.407-.658-.725-.936a4.915 4.915 0 0 0-.881-.61l-.012-.006h-.002A.5.5 0 0 1 10 7V2a.5.5 0 0 1 .295-.458 1.775 1.775 0 0 0 .351-.271c.08-.08.155-.17.214-.271H5.14c.06.1.133.191.214.271a1.78 1.78 0 0 0 .37.282z"
                ></path>
              </svg>
            </div>
            <div class="px-2">
              <h6 class="fw-bold mb-0">Location</h6>
              <p class="text-muted mb-0">Sydney, Australia</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_hero.html.erb
<header class="hero-background">
  <div class="container pt-4 pt-xl-5">
    <div class="row">
      <div
        class="col-md-12 col-xl-12 col-xxl-12 text-center text-md-start mx-auto jumbotron"
      >
        <div class="row align-items-center justify-content-center">
          <div class="col-md-6 col-xl-6 col-xxl-6 text-center text-md-start mx-auto">
            <h1 class="fw-bold">
              <span class="hero-text heading">
                Master Full Stack Development with a Seasoned Industry Mentor of
                5+ Years
              </span>
            </h1>
            <p class="fw-bolds mb-2 fw-bold subheading">
              Uncover Proven Strategies and Techniques to Excel in Your First
              Job Interview.
            </p>

            <div class="pt-5 d-flex gap-3 flex-wrap">
              <div class="btn primary-btn">
                <a
                  href="https://calendly.com/rabinpoudyal/15-minutes-get-to-know-session"
                  target="_blank"
                  class="text-light"
                  >Free 15 min session <%= image_tag "svg/videocall.svg",
                  height: 20 %>
                </a>
              </div>
              <button
                class="btn primary-btn text-light"
                data-bs-toggle="modal"
                data-bs-target="#videoModal"
              >
                See How it works
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="29"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="feather feather-play-circle"
                >
                  <circle cx="12" cy="12" r="10"></circle>
                  <polygon points="10 8 16 12 10 16 10 8"></polygon>
                </svg>
              </button>
            </div>
          </div>
          
          <div class="col-md-6 col-xl-6 col-xxl-6 text-center text-md-start mx-auto">
            <%# <img
              src="/icons/hero.png"
              alt="hero"
              class="img-fluid"
              height="500"
            /> %>
            <%= image_tag "svg/pair-program.svg", class: 'img-fluid' %>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</header>

<div
  class="modal fade"
  id="videoModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="videoModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="videoModalLabel">YouTube Video Modal</h5>
      </div>
      <div class="modal-body">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe
            class="embed-responsive-item"
            src="https://www.youtube.com/embed/N8q7XL6E93I"
            allowfullscreen
            width="100%"
            height="500"
          ></iframe>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_relearn.html.erb
<section>
  <div class="container py-5">
    <div class="row mb-5">
      <div class="text-center mx-auto">
        <h2 class="">Embrace Unlearning and Rediscover Mastery</h2>
        <div class="seperator-line mx-auto"></div>
        <p
          class="text-muted mb-5 col-md-8 col-xl-4 col-xxl-6 text-center mx-auto pt-3"
        >
          Let us guide you in shedding counterproductive habits and embracing optimal methodologies. Drawing from our insight into interviewer preferences, we'll steer you away from pitfalls like the ones below. Prepare to elevate your coding approach by refining it for enhanced readability, maintainability, and scalability—without succumbing to over-engineering.
        </p>
        <div>
          <img
            src="https://res.cloudinary.com/dpugbcmpg/image/upload/v1690451378/mistake_gn6jqp.png"
            alt="coding mistake you don't want to make in interview"
            class="img-fluid"
          />
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_service_cards.html.erb
<section class="container">
  <div class="row pt-5">
    <div class="col col-md-4">
      <div class="card bg-primary-subtle">
        <div class="card-body px-4 py-5 px-md-5">
          <div class="d-flex gap-3 justify-content-center align-items-center">
            <span>
              <%= image_tag "svg/one-on-one.svg", height: 50 %>
            </span>
            <span>
              <h5 class="fw-bold mb-3">1-on-1 Tutoring</h5>
              <p class="card-text">Tailored Guidance for Every Level of Expertise - From Novices to Seasoned Professionals. We are here to help.</p>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="col col-md-4">
      <div class="card bg-primary-subtle">
        <div class="card-body px-4 py-5 px-md-5">
            <div class="d-flex gap-3 justify-content-center align-items-center">
              <span>
                <%= image_tag "svg/high-quality.svg", height: 50 %>
              </span>
              <span>
                <h5 class="fw-bold card-title mb-3">
                  100+ HQ Resources
                </h5>
                <p class="card-text">Elevate Your Learning with Premium Resources for Mastering the Right Way to Get Things Done.</p>
              </span>
            </div>
        </div>
      </div>
    </div>
    <div class="col col-md-4">
      <div class="card bg-primary-subtle">
        <div class="card-body px-4 py-5 px-md-5">
            <div class="d-flex gap-3 justify-content-center align-items-center">
              <span>
                <%= image_tag "svg/interview.svg", height: 50 %>
              </span>
              <span>
            <h5 class="fw-bold card-title mb-3">Mock Interviews</h5>
            <p class="card-text">Sharpen Your Skills and Measure Your Growth Through Invigorating 1-on-1 Mock Interviews.</p>
          </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/abouat.html.erb
<h1>Home#abouat</h1>
<p>Find me in app/views/home/abouat.html.erb</p>

app/views/home/blog.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-md-12">
      <h1 class="h1 text-center">Blog</h1>
      <div class="seperator-line"></div>
      <p>Coming Soon...</p>
    </div>
  </div>
</div>

app/views/home/contacts.html.erb
<h1>Home#contacts</h1>
<p>Find me in app/views/home/contacts.html.erb</p>

app/views/home/curriculum.html.erb
<div class="container p-5">
<h1 class="h1 text-center">CodingTutor Curriculum</h1>
<div class="seperator-line"></div>
  <div class="row">
    <div class="col-md-12">
      <div class="path">
        <%= image_tag "svg/path.svg", class: "img-fluid" %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render partial: 'hero' %>
<%= render partial: 'service_cards' %>
<%= render partial: 'accelerate' %>


<section>
  <div class="container bg-secondary-gradient py-5">
    <div class="row">
      <div class="text-center">
        <h3 class="">Achieve Swift and Effective Results</h3>
        <div class="seperator-line mx-auto"></div>
        <p
          class="text-muted mb-5 col-md-8 col-xl-4 col-xxl-6 text-center mx-auto pt-3"
        >
          Gain Clarity on Your Current Position and Uncover Actionable Steps to Reach Your Desired Destination with Our Expert Guidance.
        </p>
      </div>
    </div>

    <div class="py-5">
      <div class="mx-auto" style="max-width: 900px">
        <div class="row row-cols-1 row-cols-md-2 d-flex justify-content-center">
          <div class="col mb-4">
            <div class="card bg-primary-subtle">
              <div class="card-body text-center px-4 py-5 px-md-5">
                <p class="fw-bold card-text mb-2">
                  Step 1: Evaluation & Progression
                </p>
                <p class="card-title mb-3">
                  Begin by gauging your existing skills as we chart a tailored roadmap to propel you toward your aspirations.
                </p>
              </div>
            </div>
          </div>
          <div class="col mb-4">
            <div class="card bg-primary-subtle">
              <div class="card-body text-center px-4 py-5 px-md-5">
                <p class="fw-bold card-text mb-2">
                  Step 2: Immersion & Review
                </p>
                <p class="card-title mb-3">
                  Immerse yourself in the learning process while consistently reviewing your progress.
                </p>
              </div>
            </div>
          </div>
          <div class="col mb-4">
            <div class="card bg-primary-subtle">
              <div class="card-body text-center px-4 py-5 px-md-5">
                <p class="fw-bold card-text mb-2">
                  Step 3: Application & Expansion
                </p>
                <p class="card-title mb-3">
                  Put your skills into action through rigorous practice while expanding your knowledge horizons.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%= render partial: 'relearn' %>

<%= render partial: 'faq' %>

<%= render partial: 'contact' %>

app/views/home/pricing.html.erb
<section class="pricing py-5">
 <h1 class="text-center">Pricing</h1>
 <div class="seperator-line"></div>
  <div class="container">
    <div class="row">
      <!-- Free Tier -->
      <div class="col-lg-3">
        <div class="card mb-5 mb-lg-0">
          <div class="card-body">
            <h5 class="card-title text-muted text-uppercase">Free</h5>
            <h6 class="card-price">$0<span class="period">/month</span></h6>
            <hr>
            <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Free Assessment</li>
            </ul>
            <a href="#" class="btn btn-block primary-btn text-uppercase">Get started</a>
          </div>
        </div>
      </div>
      <!-- Bronze Tier -->
      <div class="col-lg-3">
        <div class="card mb-5 mb-lg-0">
          <div class="card-body">
            <h5 class="card-title text-muted text-uppercase">Bronze</h5>
            <h6 class="card-price">$29<span class="period">/month</span></h6>
            <hr>
            <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Free Assessment</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Benefits</li>
            </ul>
            <a href="#" class="btn btn-block primary-btn text-uppercase">Get started</a>
          </div>
        </div>
      </div>
      <!-- Silver Tier -->
      <div class="col-lg-3">
        <div class="card mb-5 mb-lg-0">
          <div class="card-body">
            <h5 class="card-title text-muted text-uppercase">Silver</h5>
            <h6 class="card-price">$49<span class="period">/month</span></h6>
            <hr>
            <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Free Assessment</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Benefits</li>
            </ul>
            <a href="#" class="btn btn-block primary-btn text-uppercase">Get started</a>
          </div>
        </div>
      </div>
      <!-- Gold Tier -->
      <div class="col-lg-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-muted text-uppercase">Gold</h5>
            <h6 class="card-price">$99<span class="period">/month</span></h6>
            <hr>
            <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Free Assessment</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Benefits</li>
            </ul>
            <a href="#" class="btn btn-block primary-btn text-uppercase">Get started</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/projects.html.erb
<h1>Home#projects</h1>
<p>Find me in app/views/home/projects.html.erb</p>

app/views/home/services.html.erb
<h1>Home#services</h1>
<p>Find me in app/views/home/services.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Coding Tutor</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    
    <meta property="og:type" content="website">
    <meta name="description" content="Master the art of coding with CodingTutor.Online – the ultimate platform for freshers looking to dive into the world of tech. Our expert tutors provide comprehensive courses, personalized problem-solving guidance, and real-world project support. Prepare for success with mock tests and access abundant coding resources. Start your journey today and unlock endless opportunities in the exciting field of coding.">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:400,700,800&amp;display=swap">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% flash.each do |key, value| %>
      <div class="alert alert-success"><%= value %></div>
    <% end %>

    <%= render partial: 'shared/navbar' %>
    <%= yield %>
    <%= render partial: 'shared/footer' %>
  </body>
  <footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/js/bootstrap.min.js" integrity="sha512-fHY2UiQlipUq0dEabSM4s+phmn+bcxSYzXP4vAXItBvBHU7zAM/mkhCZjtBEIJexhOMzZbgFlPLuErlJF2b+0g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   <script src="https://www.google.com/recaptcha/api.js"></script>
    <script>
   function onSubmit(token) {
     document.getElementById("contact-form").submit();
   }
 </script>

  </footer>
</html>

app/views/shared/_footer.html.erb
    <footer class="footer">
        <div class="container py-4 py-lg-5">
            <div class="row justify-content-center">
                <div class="col-sm-4 col-md-6 text-center text-lg-start d-flex flex-column">
                    <h3 class="fs-6 fw-bold">🎯 We want to see you succeed</h3>
                    <ul class="list-unstyled">
                        <li>Discover a world of possibilities with our expert mentorship. Whether you're diving into development or aiming to ace interviews, we're here to guide you every step of the way. Reach out to us and embark on your journey to success today!</li>
                    </ul>
                </div>
                <div class="col-sm-4 col-md-3 text-center text-lg-start d-flex flex-column">
                    <h3 class="fs-6 fw-bold">Services</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Mentoring</a></li>
                        <li><a href="#">Web design & Development</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 text-center text-lg-start d-flex flex-column align-items-center order-first align-items-lg-start order-lg-last">
                    <%= image_tag "svg/codingtutor.png", height: "50" %> Coding Tutor
                </div>
            </div>
            <hr>
            <div class="text-muted d-flex justify-content-between align-items-center pt-3">
                <p class="mb-0 text-white">Copyright © 2023 Coding Tutor</p>
                <ul class="list-inline mb-0 d-none">
                    <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-facebook">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
                        </svg></li>
                    <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-twitter">
                            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
                        </svg></li>
                    <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-instagram">
                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
                        </svg></li>
                </ul>
            </div>
        </div>
    </footer>